### ISSUE TITLE
Unable to add new Defect to IT Logger

### ISSUE THREAD

**Issue by tototto** [AY2021S1-TIC4001-3/tp#9]
executing the following statement failed:
E.g. add t/cannot submit s/assigned sv/high dl/20Sep2020 o/Jack 

The following exception was thrown:
Exception in thread "main" java.lang.NumberFormatException: For input string: "high"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at seedu.itlogger.Parser.parseSeverity(Parser.java:83)
	at seedu.itlogger.ItLogger.main(ItLogger.java:60)

**Comment by HongJiancheng** [comment]
Hi hi, the severity was assigned as integer in Defect Class, thus, it need to be an Integer, should we change it to String instead?

**Comment by tototto** [comment]
Hi Jian Cheng,

I'm fine with integer values too. if everyone is okay let us close this issue and update our user story on fri. 02 oct 2020.
@ZhengShijieNUS @JanuariusJang @pigoliver

**Comment by HongJiancheng** [comment]
I am agree, waiting for others. Thanks thanks

**Comment by SJZheng-Abel** [comment]
I agree, too.
